#!/bin/sh
SRC_FILE=$1
DST_PATH=$2

if [ -z "$DST_PATH" ]; then
    DST_PATH=$(dirname $0)
fi

error() {
     local red="\033[1;31m"
     local normal="\033[0m"
     echo "[${red}ERROR${normal}] $1"
}

# Check ImageMagick
command -v convert >/dev/null 2>&1 || { error >&2 "The ImageMagick is not installed. Please install it first.see http://www.imagemagick.org/"; exit -1; }

if [ -z $SRC_FILE ]
  then
    echo "No argument given"
else
  convert "$SRC_FILE" -resize 18     "$DST_PATH/Icon-18.png"
  convert "$SRC_FILE" -resize 36     "$DST_PATH/Icon-18@2x.png"
  convert "$SRC_FILE" -resize 54     "$DST_PATH/Icon-18@3x.png"
fi
